name: Unzip
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dézipper
        run: unzip nzassa-skin-source.zip
      - name: Supprimer ZIP
        run: rm nzassa-skin-source.zip
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Décompression du code source
